module.exports = {
  "ground_truth": {
    "Two women are embracing while holding to go packages. | Two woman are holding packages.": "false",
    "Two women are embracing while holding to go packages. | The men are fighting outside a deli.": "true",
    "Two young children in blue jerseys, one with the number 9 and one with the number 2 are standing on wooden steps in a bathroom and washing their hands in a sink. | Two kids in numbered jerseys wash their hands.": "false",
    "Two young children in blue jerseys, one with the number 9 and one with the number 2 are standing on wooden steps in a bathroom and washing their hands in a sink. | Two kids in jackets walk to school.": "true",
    "A man selling donuts to a customer during a world exhibition event held in the city of Angeles | A woman drinks her coffee in a small cafe.": "true",
    "A man selling donuts to a customer during a world exhibition event held in the city of Angeles | A man selling donuts to a customer.": "false",
    "Two young boys of opposing teams play football, while wearing full protection uniforms and helmets. | boys play football": "false",
    "Two young boys of opposing teams play football, while wearing full protection uniforms and helmets. | dog eats out of bowl": "true",
    "A man in a blue shirt standing in front of a garage-like structure painted with geometric designs. | A man is wearing a blue shirt": "false",
    "A man in a blue shirt standing in front of a garage-like structure painted with geometric designs. | A man is wearing a black shirt": "true",
    "Under a blue sky with white clouds, a child reaches up to touch the propeller of a plane standing parked on a field of grass. | A child is reaching to touch the propeller of a plane.": "false",
    "Under a blue sky with white clouds, a child reaches up to touch the propeller of a plane standing parked on a field of grass. | A child is playing with a ball.": "true",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is doing a cartwheel.": "false",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is fixing her home.": "true",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is doing a cartwheel and falls on her head.": "true",
    "Two men on bicycles competing in a race. | People are riding bikes.": "false",
    "Two men on bicycles competing in a race. | A few people are catching fish.": "true",
    "A young boy in a field of flowers carrying a ball | boy in field": "false",
    "A young boy in a field of flowers carrying a ball | dog in pool": "true",
    "Families waiting in line at an amusement park for their turn to ride. | The restaurant is very bad.": "true",
    "Families waiting in line at an amusement park for their turn to ride. | People are waiting in line at a restaurant.": "true",
    "Families waiting in line at an amusement park for their turn to ride. | People are waiting to see a movie.": "true",
    "A senior is waiting at the window of a restaurant that serves sandwiches. | A person waits to be served his food.": "false",
    "A senior is waiting at the window of a restaurant that serves sandwiches. | A man is waiting in line for the bus.": "true",
    "Man in a black suit, white shirt and black bowtie playing an instrument with the rest of his symphony surrounding him. | A person in a suit": "false",
    "Man in a black suit, white shirt and black bowtie playing an instrument with the rest of his symphony surrounding him. | Nobody has a suit": "true",
    "Two women having drinks and smoking cigarettes at the bar. | Two women are at a bar.": "false",
    "Two women having drinks and smoking cigarettes at the bar. | Three women are at a bar.": "true",
    "At an outdoor event in an Asian-themed area, a crowd congregates as one person in a yellow Chinese dragon costume confronts the camera. | A single man is next to a camera": "true",
    "Two doctors perform surgery on patient. | Two surgeons are having lunch.": "true",
    "Two doctors perform surgery on patient. | Doctors are performing surgery.": "false",
    "A white dog with long hair jumps to catch a red and green toy. | A white dog with long hair is swimming underwater.": "true",
    "A white dog with long hair jumps to catch a red and green toy. | An animal is jumping to catch an object.": "false",
    "Kids are on a amusement ride. | A car is broke down on the side of the road.": "true",
    "Kids are on a amusement ride. | Kids ride an amusement ride.": "false",
    "A man in a black shirt is playing golf outside. | The man in the black shirt trades Pokemon cards with his girlfriend.": "true",
    "A man in a black shirt is playing golf outside. | The man wearing the black shirt plays a game of golf.": "false",
    "A older gentleman finds it humorous that he is getting his picture taken while doing his laundry. | a guy laughs while doing laundry": "false",
    "A older gentleman finds it humorous that he is getting his picture taken while doing his laundry. | two ladies pin clothes to dry": "true",
    "An Indian woman is washing and cleaning dirty laundry at a lake and in the background is a kid who appears to have jumped into the lake. | An Indian woman is doing her laundry in a lake.": "false",
    "An Indian woman is washing and cleaning dirty laundry at a lake and in the background is a kid who appears to have jumped into the lake. | An Indian woman is putting her laundry into the machine.": "true",
    "A man in a green jersey and rollerskates stumbles as a man in a black jersey appears to collide with him. | They are driving cars.": "true",
    "A man in a green jersey and rollerskates stumbles as a man in a black jersey appears to collide with him. | The man stumbles stumbles in rollerskates.": "false",
    "A group of onlookers glance at a person doing a strange trick on her head. | A boy does a card trick.": "true",
    "A group of onlookers glance at a person doing a strange trick on her head. | People watch another person do a trick.": "false",
    "The middle eastern woman wearing the pink headscarf is walking beside a woman in a purple headscarf. | Only one woman is wearing a head scarf.": "true",
    "A taxi SUV drives past an urban construction site, as a man walks down the street in the other direction. | A man is chasing an SUV that is going in the same direction as him.": "true",
    "A taxi SUV drives past an urban construction site, as a man walks down the street in the other direction. | An SUV and a man are going in opposite directions.": "false",
    "People wearing red shirts are standing in a large pool of water as it splashes over and around them. | Nobody has a shirt on": "true",
    "People wearing red shirts are standing in a large pool of water as it splashes over and around them. | A person in a shirt": "false",
    "A man in a white t-shirt takes a picture in the middle of the street with two public buses in the background. | A man is wearing a black shirt": "true",
    "A man in a white t-shirt takes a picture in the middle of the street with two public buses in the background. | A man is wearing a white shirt": "false",
    "A shirtless man is singing into a microphone while a woman next to him plays an accordion. | He is playing a saxophone.": "true",
    "A shirtless man is singing into a microphone while a woman next to him plays an accordion. | A man is singing into a microphone.": "false",
    "Women and children sitting outside in the shade while a group of younger children sitting inside in the shade. | The woman and kids and sitting down.": "false",
    "Women and children sitting outside in the shade while a group of younger children sitting inside in the shade. | The woman is running.": "true",
    "A pregnant lady singing on stage while holding a flag behind her. | A woman is sick in bed.": "true",
    "A pregnant lady singing on stage while holding a flag behind her. | A woman is making music.": "false",
    "The two farmers are working on a piece of John Deere equipment. | Men are working on John Deere equipment": "false",
    "The two farmers are working on a piece of John Deere equipment. | John Deere equipment is being worked on by two farmers": "false",
    "The two farmers are working on a piece of John Deere equipment. | 2 Men are making a pool together": "true",
    "A little boy in a blue shirt holding a toy. | Boy dressed in red lighting things on fire.": "true",
    "A little boy in a blue shirt holding a toy. | Boy dressed in blue holds a toy.": "false",
    "A woman is writing something on a post-it note which is hanging on a bulletin board with a lot of other post-it notes. | The woman is talking on the phone.": "true",
    "A woman is writing something on a post-it note which is hanging on a bulletin board with a lot of other post-it notes. | The woman is writing a note.": "false",
    "A baby at the end of a slip and slide at a party | The baby is wet.": "false",
    "A baby at the end of a slip and slide at a party | The man is at the end of the slip and slide": "true",
    "A baby at the end of a slip and slide at a party | There is a party": "false",
    "A girl swings high in the air. | A girl is laying in the pool": "true",
    "A girl swings high in the air. | A girl is on a swing": "false",
    "A view of the back of a woman having a beverage. | woman dumps the drink on a man": "true",
    "A view of the back of a woman having a beverage. | woman has a drink": "false",
    "A lady sitting on a bench that is against a building and under a poster of a man in a uniform waving. | A person sitting": "false",
    "A lady sitting on a bench that is against a building and under a poster of a man in a uniform waving. | Nobody is sitting": "true",
    "A man with a shopping cart is studying the shelves in a supermarket aisle. | A man is watching a movie in a theater.": "true",
    "A man with a shopping cart is studying the shelves in a supermarket aisle. | There is a man inside a supermarket.": "false",
    "A man wearing sunglasses is sitting on the steps outside, reading a magazine. | The man is sitting.": "false",
    "A man wearing sunglasses is sitting on the steps outside, reading a magazine. | The man is reading a spoon with the words \"HELP ME\" on it.": "true",
    "A woman sitting outside weaving a long piece of red, white, and blue cloth. | He is jumping over a house": "true",
    "A woman sitting outside weaving a long piece of red, white, and blue cloth. | She is working with cloth": "false",
    "A person powerwashing stairs leading down to a pool. | a person washes stairs": "false",
    "A person powerwashing stairs leading down to a pool. | a worker cleans near the pool": "false",
    "A person powerwashing stairs leading down to a pool. | a dog chases a cat": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is falling off his bike.": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is on a boat.": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is on a beach.": "false",
    "Two black little boys hanging over an upside down bicycle, one examining the pedal. | Children were looking at a bike.": "false",
    "Two black little boys hanging over an upside down bicycle, one examining the pedal. | Someone is riding a bike.": "true",
    "A brown a dog and a black dog in the edge of the ocean with a wave under them boats are on the water in the background. | The pets are sleeping on the grass.": "true",
    "A brown a dog and a black dog in the edge of the ocean with a wave under them boats are on the water in the background. | The dogs are swimming among the boats.": "false",
    "A group of people prepare hot air balloons for takeoff. | A group of people are outside.": "false",
    "A group of people prepare hot air balloons for takeoff. | A group of people prepare cars for racing.": "true",
    "Men stand on steps leading out of a body of water | Men are standing on some steps near some water.": "false",
    "Men stand on steps leading out of a body of water | Men are sitting outside near a golf course.": "true",
    "A group of young people with instruments are on stage. | Young people are playing water polo.": "true",
    "A long-beaked bird in mid-flight. | A bird flying.": "false",
    "A long-beaked bird in mid-flight. | A rat running on a wheel.": "true",
    "A man in the middle east with a corn-on-the-cob cart selling corn. | In the middle east, a man sells corn-on-the-cob from a cart.": "false",
    "A man in the middle east with a corn-on-the-cob cart selling corn. | A middle east man is throwing corn at strangers.": "true",
    "A man in a black shirt is playing a guitar. | He is playing a song.": "false"
  },
  "detected_contradictions": {
    "Two women are embracing while holding to go packages. | Two woman are holding packages.": "false",
    "Two women are embracing while holding to go packages. | The men are fighting outside a deli.": "true",
    "Two young children in blue jerseys, one with the number 9 and one with the number 2 are standing on wooden steps in a bathroom and washing their hands in a sink. | Two kids in numbered jerseys wash their hands.": "false",
    "Two young children in blue jerseys, one with the number 9 and one with the number 2 are standing on wooden steps in a bathroom and washing their hands in a sink. | Two kids in jackets walk to school.": "true",
    "A man selling donuts to a customer during a world exhibition event held in the city of Angeles | A woman drinks her coffee in a small cafe.": "true",
    "A man selling donuts to a customer during a world exhibition event held in the city of Angeles | A man selling donuts to a customer.": "false",
    "Two young boys of opposing teams play football, while wearing full protection uniforms and helmets. | boys play football": "false",
    "Two young boys of opposing teams play football, while wearing full protection uniforms and helmets. | dog eats out of bowl": "true",
    "A man in a blue shirt standing in front of a garage-like structure painted with geometric designs. | A man is wearing a blue shirt": "false",
    "A man in a blue shirt standing in front of a garage-like structure painted with geometric designs. | A man is wearing a black shirt": "true",
    "Under a blue sky with white clouds, a child reaches up to touch the propeller of a plane standing parked on a field of grass. | A child is reaching to touch the propeller of a plane.": "false",
    "Under a blue sky with white clouds, a child reaches up to touch the propeller of a plane standing parked on a field of grass. | A child is playing with a ball.": "true",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is doing a cartwheel.": "false",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is fixing her home.": "true",
    "A woman is doing a cartwheel while wearing a bikini in the sand next to the beach. | A woman is doing a cartwheel and falls on her head.": "false",
    "Two men on bicycles competing in a race. | People are riding bikes.": "false",
    "Two men on bicycles competing in a race. | A few people are catching fish.": "true",
    "A young boy in a field of flowers carrying a ball | boy in field": "false",
    "A young boy in a field of flowers carrying a ball | dog in pool": "true",
    "Families waiting in line at an amusement park for their turn to ride. | The restaurant is very bad.": "true",
    "Families waiting in line at an amusement park for their turn to ride. | People are waiting in line at a restaurant.": "false",
    "Families waiting in line at an amusement park for their turn to ride. | People are waiting to see a movie.": "true",
    "A senior is waiting at the window of a restaurant that serves sandwiches. | A person waits to be served his food.": "false",
    "A senior is waiting at the window of a restaurant that serves sandwiches. | A man is waiting in line for the bus.": "true",
    "Man in a black suit, white shirt and black bowtie playing an instrument with the rest of his symphony surrounding him. | A person in a suit": "true",
    "Man in a black suit, white shirt and black bowtie playing an instrument with the rest of his symphony surrounding him. | Nobody has a suit": "true",
    "Two women having drinks and smoking cigarettes at the bar. | Two women are at a bar.": "false",
    "Two women having drinks and smoking cigarettes at the bar. | Three women are at a bar.": "false",
    "At an outdoor event in an Asian-themed area, a crowd congregates as one person in a yellow Chinese dragon costume confronts the camera. | A single man is next to a camera": "true",
    "Two doctors perform surgery on patient. | Two surgeons are having lunch.": "false",
    "Two doctors perform surgery on patient. | Doctors are performing surgery.": "false",
    "A white dog with long hair jumps to catch a red and green toy. | A white dog with long hair is swimming underwater.": "true",
    "A white dog with long hair jumps to catch a red and green toy. | An animal is jumping to catch an object.": "false",
    "Kids are on a amusement ride. | A car is broke down on the side of the road.": "true",
    "Kids are on a amusement ride. | Kids ride an amusement ride.": "false",
    "A man in a black shirt is playing golf outside. | The man in the black shirt trades Pokemon cards with his girlfriend.": "true",
    "A man in a black shirt is playing golf outside. | The man wearing the black shirt plays a game of golf.": "false",
    "A older gentleman finds it humorous that he is getting his picture taken while doing his laundry. | a guy laughs while doing laundry": "false",
    "A older gentleman finds it humorous that he is getting his picture taken while doing his laundry. | two ladies pin clothes to dry": "true",
    "An Indian woman is washing and cleaning dirty laundry at a lake and in the background is a kid who appears to have jumped into the lake. | An Indian woman is doing her laundry in a lake.": "false",
    "An Indian woman is washing and cleaning dirty laundry at a lake and in the background is a kid who appears to have jumped into the lake. | An Indian woman is putting her laundry into the machine.": "false",
    "A man in a green jersey and rollerskates stumbles as a man in a black jersey appears to collide with him. | They are driving cars.": "true",
    "A man in a green jersey and rollerskates stumbles as a man in a black jersey appears to collide with him. | The man stumbles stumbles in rollerskates.": "false",
    "A group of onlookers glance at a person doing a strange trick on her head. | A boy does a card trick.": "true",
    "A group of onlookers glance at a person doing a strange trick on her head. | People watch another person do a trick.": "false",
    "The middle eastern woman wearing the pink headscarf is walking beside a woman in a purple headscarf. | Only one woman is wearing a head scarf.": "true",
    "A taxi SUV drives past an urban construction site, as a man walks down the street in the other direction. | A man is chasing an SUV that is going in the same direction as him.": "false",
    "A taxi SUV drives past an urban construction site, as a man walks down the street in the other direction. | An SUV and a man are going in opposite directions.": "false",
    "People wearing red shirts are standing in a large pool of water as it splashes over and around them. | Nobody has a shirt on": "true",
    "People wearing red shirts are standing in a large pool of water as it splashes over and around them. | A person in a shirt": "true",
    "A man in a white t-shirt takes a picture in the middle of the street with two public buses in the background. | A man is wearing a black shirt": "true",
    "A man in a white t-shirt takes a picture in the middle of the street with two public buses in the background. | A man is wearing a white shirt": "false",
    "A shirtless man is singing into a microphone while a woman next to him plays an accordion. | He is playing a saxophone.": "true",
    "A shirtless man is singing into a microphone while a woman next to him plays an accordion. | A man is singing into a microphone.": "false",
    "Women and children sitting outside in the shade while a group of younger children sitting inside in the shade. | The woman and kids and sitting down.": "false",
    "Women and children sitting outside in the shade while a group of younger children sitting inside in the shade. | The woman is running.": "true",
    "A pregnant lady singing on stage while holding a flag behind her. | A woman is sick in bed.": "true",
    "A pregnant lady singing on stage while holding a flag behind her. | A woman is making music.": "true",
    "The two farmers are working on a piece of John Deere equipment. | Men are working on John Deere equipment": "false",
    "The two farmers are working on a piece of John Deere equipment. | John Deere equipment is being worked on by two farmers": "false",
    "The two farmers are working on a piece of John Deere equipment. | 2 Men are making a pool together": "true",
    "A little boy in a blue shirt holding a toy. | Boy dressed in red lighting things on fire.": "true",
    "A little boy in a blue shirt holding a toy. | Boy dressed in blue holds a toy.": "false",
    "A woman is writing something on a post-it note which is hanging on a bulletin board with a lot of other post-it notes. | The woman is talking on the phone.": "true",
    "A woman is writing something on a post-it note which is hanging on a bulletin board with a lot of other post-it notes. | The woman is writing a note.": "false",
    "A baby at the end of a slip and slide at a party | The baby is wet.": "true",
    "A baby at the end of a slip and slide at a party | The man is at the end of the slip and slide": "false",
    "A baby at the end of a slip and slide at a party | There is a party": "false",
    "A girl swings high in the air. | A girl is laying in the pool": "true",
    "A girl swings high in the air. | A girl is on a swing": "false",
    "A view of the back of a woman having a beverage. | woman dumps the drink on a man": "true",
    "A view of the back of a woman having a beverage. | woman has a drink": "false",
    "A lady sitting on a bench that is against a building and under a poster of a man in a uniform waving. | A person sitting": "true",
    "A lady sitting on a bench that is against a building and under a poster of a man in a uniform waving. | Nobody is sitting": "true",
    "A man with a shopping cart is studying the shelves in a supermarket aisle. | A man is watching a movie in a theater.": "true",
    "A man with a shopping cart is studying the shelves in a supermarket aisle. | There is a man inside a supermarket.": "false",
    "A man wearing sunglasses is sitting on the steps outside, reading a magazine. | The man is sitting.": "true",
    "A man wearing sunglasses is sitting on the steps outside, reading a magazine. | The man is reading a spoon with the words \"HELP ME\" on it.": "true",
    "A woman sitting outside weaving a long piece of red, white, and blue cloth. | He is jumping over a house": "true",
    "A woman sitting outside weaving a long piece of red, white, and blue cloth. | She is working with cloth": "false",
    "A person powerwashing stairs leading down to a pool. | a person washes stairs": "false",
    "A person powerwashing stairs leading down to a pool. | a worker cleans near the pool": "false",
    "A person powerwashing stairs leading down to a pool. | a dog chases a cat": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is falling off his bike.": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is on a boat.": "true",
    "A person rides his bicycle in the sand beside the ocean. | A person is on a beach.": "false",
    "Two black little boys hanging over an upside down bicycle, one examining the pedal. | Children were looking at a bike.": "false",
    "Two black little boys hanging over an upside down bicycle, one examining the pedal. | Someone is riding a bike.": "true",
    "A brown a dog and a black dog in the edge of the ocean with a wave under them boats are on the water in the background. | The pets are sleeping on the grass.": "true",
    "A brown a dog and a black dog in the edge of the ocean with a wave under them boats are on the water in the background. | The dogs are swimming among the boats.": "false",
    "A group of people prepare hot air balloons for takeoff. | A group of people are outside.": "true",
    "A group of people prepare hot air balloons for takeoff. | A group of people prepare cars for racing.": "true",
    "Men stand on steps leading out of a body of water | Men are standing on some steps near some water.": "false",
    "Men stand on steps leading out of a body of water | Men are sitting outside near a golf course.": "true",
    "A group of young people with instruments are on stage. | Young people are playing water polo.": "true",
    "A long-beaked bird in mid-flight. | A bird flying.": "false",
    "A long-beaked bird in mid-flight. | A rat running on a wheel.": "true",
    "A man in the middle east with a corn-on-the-cob cart selling corn. | In the middle east, a man sells corn-on-the-cob from a cart.": "false",
    "A man in the middle east with a corn-on-the-cob cart selling corn. | A middle east man is throwing corn at strangers.": "false",
    "A man in a black shirt is playing a guitar. | He is playing a song.": "false"
  }
}